//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPExchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVEL
    {
        public LEVEL()
        {
            this.Post = new HashSet<Post>();
            this.User = new HashSet<User>();
        }
    
        public System.Guid LevelId { get; set; }
        public string LevelType { get; set; }
        public Nullable<byte> Value { get; set; }
    
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
