//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPExchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public System.Guid RatingId { get; set; }
        public Nullable<System.Guid> PostId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<byte> Rating1 { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
