//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPExchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ListBookmarkPost = new HashSet<Bookmark>();
            this.ListCreatedMessage = new HashSet<Message>();
            this.ListSendMessages = new HashSet<Message>();
            this.Message2 = new HashSet<Message>();
            this.ListReceivedMessage = new HashSet<Message>();
            this.Order = new HashSet<Order>();
            this.Order1 = new HashSet<Order>();
            this.Order2 = new HashSet<Order>();
            this.Post = new HashSet<Post>();
            this.Post1 = new HashSet<Post>();
            this.Post2 = new HashSet<Post>();
            this.PostComment = new HashSet<PostComment>();
            this.PostComment1 = new HashSet<PostComment>();
            this.Rating1 = new HashSet<Rating>();
            this.UserDetail = new HashSet<UserDetail>();
            this.UserDetail1 = new HashSet<UserDetail>();
            this.User1 = new HashSet<User>();
            this.User11 = new HashSet<User>();
        }
    
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Fullname { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> UserDetailId { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> LevelId { get; set; }
        public Nullable<byte> Role { get; set; }
    
        public virtual ICollection<Bookmark> ListBookmarkPost { get; set; }
        public virtual LEVEL Level { get; set; }
        public virtual ICollection<Message> ListCreatedMessage { get; set; }
        public virtual ICollection<Message> ListSendMessages { get; set; }
        public virtual ICollection<Message> Message2 { get; set; }
        public virtual ICollection<Message> ListReceivedMessage { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Order> Order1 { get; set; }
        public virtual ICollection<Order> Order2 { get; set; }
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<Post> Post1 { get; set; }
        public virtual ICollection<Post> Post2 { get; set; }
        public virtual ICollection<PostComment> PostComment { get; set; }
        public virtual ICollection<PostComment> PostComment1 { get; set; }
        public virtual ICollection<Rating> Rating1 { get; set; }
        public virtual ICollection<UserDetail> UserDetail { get; set; }
        public virtual ICollection<UserDetail> UserDetail1 { get; set; }
        public virtual UserDetail UserDetail2 { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<User> User11 { get; set; }
        public virtual User User3 { get; set; }
    }
}
