//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.ListChildCategory = new HashSet<CATEGORY>();
            this.ListPost = new HashSet<Post>();
        }
        
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<byte> Index { get; set; }
    
        public virtual ICollection<CATEGORY> ListChildCategory { get; set; }
        public virtual CATEGORY Parent { get; set; }
        public virtual ICollection<Post> ListPost { get; set; }
    }
}
