//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVEL
    {
        public LEVEL()
        {
            this.ListPost = new HashSet<Post>();
            this.ListUser = new HashSet<User>();
        }
    
        public int LevelId { get; set; }
        public string LevelType { get; set; }
        public Nullable<byte> Value { get; set; }
    
        public virtual ICollection<Post> ListPost { get; set; }
        public virtual ICollection<User> ListUser { get; set; }
    }
}
