//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public System.Guid MediaId { get; set; }
        public Nullable<System.Guid> PostId { get; set; }
        public string MediaLink { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> Index { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
