//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public int UserFromId { get; set; }
        public Nullable<int> UserToId { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public Nullable<byte> ImportantLevel { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual User CreatedUser { get; set; }
        public virtual User UserFrom { get; set; }
        public virtual User ModifiedUser { get; set; }
        public virtual User UserTo { get; set; }
    }
}
