//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Bookmark = new HashSet<Bookmark>();
            this.Media = new HashSet<Media>();
            this.Order = new HashSet<Order>();
            this.PostComment = new HashSet<PostComment>();
            this.PostLocation = new HashSet<PostLocation>();
            this.PostTag = new HashSet<PostTag>();
            this.Rating = new HashSet<Rating>();
        }
    
        public System.Guid PostId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceSale { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> LevelId { get; set; }
    
        public virtual ICollection<Bookmark> Bookmark { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual ICollection<Media> Media { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<PostComment> PostComment { get; set; }
        public virtual ICollection<PostLocation> PostLocation { get; set; }
        public virtual ICollection<PostTag> PostTag { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
