//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ListBookmark = new HashSet<Bookmark>();
            this.ListSendMessage = new HashSet<Message>();
            this.ListReceivedMessage = new HashSet<Message>();
            this.ListOrder = new HashSet<Order>();
            this.ListCreatedOrder = new HashSet<Order>();
            this.ListOwnerPost = new HashSet<Post>();
            this.ListCreatedPost = new HashSet<Post>();
            this.ListRating = new HashSet<Rating>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Fullname { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> UserDetailId { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<byte> Role { get; set; }
    
        public virtual ICollection<Bookmark> ListBookmark { get; set; }
        public virtual LEVEL Level { get; set; }
        public virtual ICollection<Message> ListSendMessage { get; set; }
        public virtual ICollection<Message> ListReceivedMessage { get; set; }
        public virtual ICollection<Order> ListOrder { get; set; }
        public virtual ICollection<Order> ListCreatedOrder { get; set; }
        public virtual ICollection<Post> ListOwnerPost { get; set; }
        public virtual ICollection<Post> ListCreatedPost { get; set; }
        public virtual ICollection<Rating> ListRating { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual User ModifiedUser { get; set; }
        public virtual User CreatedUser { get; set; }
    }
}
