//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ListBookmark = new HashSet<Bookmark>();
            this.ListSendMessage = new HashSet<Message>();
            this.ListReceiveMessage = new HashSet<Message>();
            this.ListOrder = new HashSet<Order>();
            this.ListPost = new HashSet<Post>();
        }
    
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Fullname { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> UserDetailId { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> LevelId { get; set; }
        public Nullable<byte> Role { get; set; }
    
        public virtual ICollection<Bookmark> ListBookmark { get; set; }
        public virtual LEVEL Level { get; set; }
        public virtual ICollection<Message> ListSendMessage { get; set; }
        public virtual ICollection<Message> ListReceiveMessage { get; set; }
        public virtual ICollection<Order> ListOrder { get; set; }
        public virtual ICollection<Post> ListPost { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual User ModifiedUser { get; set; }
        public virtual User CreatedUser { get; set; }
    }
}
